use_frameworks!
source 'https://github.com/iFlyCai/IFLYSpecs.git' # 私有库的 Podspec 仓库
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

target 'IFLYGiteeFollowers_Example' do
  pod 'IFLYGiteeFollowers', :path => '../'

  target 'IFLYGiteeFollowers_Tests' do
    inherit! :search_paths
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        end
      end
    end
  end
end
