use_frameworks!

platform :ios, '10.0'

target 'IFLYGiteeFollowers_Example' do
  pod 'IFLYGiteeFollowers', :path => '../'

  target 'IFLYGiteeFollowers_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
